spring:
  datasource:
    url: jdbc:mysql://cslmysql.ccaygbumrmq7.ap-northeast-2.rds.amazonaws.com:3306/csldb?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: csluser
    password: csl2016!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

